// src/js/constants/action-types.js
export const ADD_ARTICLE = "ADD_ARTICLE";
export const FETCH_IMAGES_BEGIN = 'FETCH_IMAGES_BEGIN';
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS';
export const FETCH_IMAGES_FAILURE = 'FETCH_IMAGES_FAILURE';
export const UPDATE_IMAGE_TITLE_SUCCESS = 'UPDATE_IMAGE_TITLE_SUCCESS';
export const UPDATE_IMAGE_TITLE_BEGIN = 'UPDATE_IMAGE_TITLE_BEGIN';
export const UPDATE_IMAGE_TITLE_FAILURE = 'UPDATE_IMAGE_TITLE_FAILURE';


export const SERVICE_URL = 'http://localhost:8000';